site_name: Docs - ChamaControl
theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle: 
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: orange
      accent: amber 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: orange
      accent: lime


nav:
  - Home : index.md
  - Como Contribuir?: CONTRIBUTING.md
  # - Estudos : 
  #    - Sobre : estudos/README.md
  #    - Scrum: estudos/2020-Scrum-Guide-PortugueseBR-3.0.pdf
  #    - Metodologias ágeis: estudos/Metodologias_ágeis.md
  #    - Arquitetura : estudos/coelhos/arquitetura.md
  #    - Requisitos : estudos/coelhos/requisitos.md
  - Arquitetura: arquitetura.md
  - Story Map: storymap.md
  - Protótipo: prototipo.md
  - Sprints :
     - Sprint 0 : sprints/Sprint-0.md
     - Sprint 1: sprints/Sprint-1.md
     - Sprint 2: sprints/Sprint-2.md
     - Sprint 3: sprints/Sprint-3.md
     - Sprint 4: sprints/Sprint-4.md
     - Sprint 5: sprints/Sprint-5.md 
     - Sprint 6: sprints/Sprint-6.md
     - Sprint 7: sprints/Sprint-7.md
  

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list




  
