name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Change directory to backend
      run: cd backend

    - name: Install dependencies
      run: npm install
      working-directory: backend

    - name: Run linter
      run: npm run lint
      working-directory: backend

    - name: Run tests
      run: npm test
      working-directory: backend
